version: '3'

services:
  nextjs-app:
    container_name: yijing-design-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - yijing-network
    volumes:
      - ./data:/app/data
    depends_on:
      - mysql

  mysql:
    container_name: yijing-design-mysql
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /www/wwwroot/site002-data/mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - yijing-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  nginx:
    container_name: yijing-design-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - nextjs-app
    networks:
      - yijing-network
    restart: always

networks:
  yijing-network:
    driver: bridge 